[package]
name = "usdt"
version = "0.1.0"
edition = "2021"

[dependencies]
probe = "0.5.1"

[build-dependencies]
cbindgen = "0.27.0"

[lib]
name = "usdt"
crate_type = ["staticlib"]

[profile.release]
codegen-units = 1
lto = true
strip = true
rpath = false
